language: java

jdk:
- oraclejdk9

env:
- TERM=dumb

after_success:
- ./gradlew jacocoTestReport coveralls

notifications:
  email:
    - stephan@syntaktischer-zucker.de
  on_success: always
  on_failure: always
