language: java

jdk:
- oraclejdk8

env:
- TERM=dumb

script:
- ./gradlew jar

after_success:
- ./gradlew jacocoTestReport coveralls

notifications:
  email:
    - stephan@syntaktischer-zucker.de
  on_success: always
  on_failure: always
